image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore backend/DocStore.sln 
      dotnet build backend/DocStore.sln
  - name: Run
    command: dotnet run --project backend/src/WebApi/WebApi.csproj

vscode:
  extensions:
    - muhammad-sammy.csharp

ports:
  - port: 5002
    onOpen: "open-browser"
    name: ssl port
    description: Web API

  - port: 5001
    onOpen: "ignore"