image:
  file: .gitpod.Dockerfile

tasks:

  - name: Restore
    before: |
      dotnet dev-certs https 
      dotnet restore backend/DocStore.sln  
    init: dotnet build backend/DocStore.sln
    command: dotnet run --project backend/src/WebApi/WebApi.csproj

  - name: Docker
    command: docker-compose -f backend/docker-compose-db.yml up
      
vscode:
  extensions:
    - muhammad-sammy.csharp
    - sdras.night-owl
    - humao.rest-client
    - ms-azuretools.vscode-docker
    - ckolkman.vscode-postgres
    - rangav.vscode-thunder-client
    - vscode-icons-team.vscode-icons
    - patcx.vscode-nuget-gallery
    
ports:

  - port: 5002
    onOpen: "ignore"
    name: ssl port
    description: Web API

  - port: 5001
    onOpen: "ignore"

  - port: 5000
    onOpen: "ignore"
    name: api debug 
    description: Web API Debug 
    visibility: public

  - port: 5432
    name: db
    description: Pstrgres
    onOpen: "ignore"
