image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp

ports:
  - port: 5002
    onOpen: "open-browser"
  - port: 5001
    onOpen: "ignore"