version: '3.4'

services:

  postgres-db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=docdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: WebApi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - postgres-db
